# Singularity definition For an SL& os capable of running the ILCSoft
# environment, including CED. (Additionally supports python3).

bootstrap: docker

from: cern/slc6-base

# This command assumes at least singularity 2.3. Used only for run, not build.
%environment
    #PATH="/usr/local/miniconda3/bin:$PATH"

%post
    yum update -y

    # For CED
    yum groupinstall -y 'Development Tools'
    yum install -y freeglut mesa-libGLU

    # For python3 in SL6
    # yum groupinstall -y 'Development Tools' # Already from CED.
    yum -y install wget tar zlib-devel
    PY_VER=3.8.0
    wget https://www.python.org/ftp/python/$PY_VER/Python-$PY_VER.tar.xz
    tar xf Python-$PY_VER.tar.xz
    cd Python-$PY_VER
    ./configure
    make
    # Install would overwrite default python2, needed e.g. by yum.
    make altinstall

    # Make python3.8 callable as python3.
    ln -s /usr/local/bin/python3.8 /usr/bin/python3
    #alias python3=python3.8

%runscript
    source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-02/init_ilcsoft.sh
    exec /bin/bash